{{- if .Values.marketingConsole.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketing-console
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gentrail.labels" (merge (dict "component" "marketing-console") .) | indent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.marketingConsole | quote }}
{{- end }}
