{{- if .Values.ingress.targetGroups.otelArn }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: authproxy
  namespace: {{ .Release.Namespace }}
spec:
  serviceRef:
    name: authproxy
    port: 4318
  targetGroupARN: {{ .Values.ingress.targetGroups.otelArn | quote }}
  targetType: ip
{{- end }}
