{{- if or .Values.ingress.otelHost .Values.ingress.otelInternal }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authproxy
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ if .Values.ingress.otelInternal }}internal{{ else }}internet-facing{{ end }}
    alb.ingress.kubernetes.io/target-type: ip
    {{- if .Values.ingress.certArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certArn | quote }}
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-3-2021-06
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{- end }}
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authproxy
                port: { number: 4318 }
      {{- if .Values.ingress.otelHost }}
      host: {{ .Values.ingress.otelHost | quote }}
      {{- end }}
{{- end }}
