#!/usr/bin/env bash
# Generate a Helm values fragment from a substrate CFN stack's outputs.
#
# Usage:
#   ./cfn-to-values.sh <substrate-stack-name> > values.yaml
set -euo pipefail

STACK_NAME="${1:?usage: $0 <substrate-stack-name>}"

OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Outputs' --output json)

val () {
    echo "$OUTPUTS" | jq -r --arg k "$1" '.[] | select(.OutputKey==$k) | .OutputValue'
}

REGION="${AWS_REGION:-$(aws configure get region)}"

cat <<YAML
# Auto-generated by cfn-to-values.sh from CFN stack ${STACK_NAME}.
# Edit at your own risk; re-run cfn-to-values.sh to regenerate.

# EKS: the managed pod-identity webhook injects IRSA creds (no in-pod token
# injection), and an in-cluster Job mints the RDS secret.
mode: eks

aws:
  region: ${REGION}

# EKS ingress is the ALB (the dashboard/authproxy Ingress templates), not the
# cloudflared tunnel.
cloudflared:
  enabled: false

image:
  registry: public.ecr.aws/p6a2v1k1
  tag: v0.2.0-rc.10

# Quoted so an empty CFN output renders as "" (a valid string for the chart
# schema) rather than a bare null. certArn is empty when no cert was passed; the
# ALB Ingress only needs it when TLS terminates there.
ingress:
  host: "$(val Hostname)"
  certArn: "$(val AcmCertArn)"
  otelHost: "$(val OtelHostname)"

ddb:
  tablePrefix: $(val DdbTablePrefix)

s3:
  evidenceBucket: $(val EvidenceBucketName)

rds:
  endpoint: $(val RdsEndpoint)
  secretArn: $(val RdsSecretArn)

llm:
  provider: bedrock
  model: $(val BedrockModelId)

irsa:
  dashboard:    $(val DashboardIrsaRoleArn)
  policyEngine: $(val PolicyEngineIrsaRoleArn)
  evaluator:    $(val EvaluatorIrsaRoleArn)
  authproxy:    $(val AuthproxyIrsaRoleArn)
  rdsBootstrap: $(val RdsBootstrapIrsaRoleArn)

# Customer must set:
#   license.secretRef: <name of Secret holding the JWT>
#   image.pullSecret:  <optional, if mirroring to private registry>
license:
  secretRef: gentrail-license

audit:
  pvcSize: 10Gi
YAML
