apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-engine
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gentrail.labels" (merge (dict "component" "policy-engine") .) | indent 4 }}
{{- if .Values.irsa.policyEngine }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.policyEngine | quote }}
{{- end }}
